version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-blog-site-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1chbleirdq458"
s3_prefix = "my-blog-site-sam"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
