AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Blogs-App Cloud Services
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetBlogsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/lambda/get-blogs
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Description: Returns a list of blogs
      MemorySize: 128
      Events:
        GetBlogs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /blogs
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetBlogsApi:
    Description: "API Gateway endpoint URL for for GetBlogs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/hello/"
  GetBlogsFunction:
    Description: "GetBlogs Lambda Function ARN"
    Value: !GetAtt GetBlogsFunction.Arn
  GetBlogsFunctionIamRole:
    Description: "Implicit IAM Role created for GetBlogs function"
    Value: !GetAtt GetBlogsFunctionRole.Arn
